[package]
name = "rest-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.5", features = ["postgres", "runtime-actix-native-tls"] }
uuid = "0.8"
dotenv = "0.15"

