[package]
name = "satoru-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
starknet = "0.7"
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
dotenv = "0.15"
url = "2"
hex = "0.4"