name: Build and check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Format code
        run: cargo fmt -- --check
        working-directory: keeper

      - name: Check code
        run: cargo check
        working-directory: keeper

      - name: Clippy
        run: cargo clippy -- -D warnings
        working-directory: keeper

      - name: Build
        run: cargo build
        working-directory: keeper